### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by slxienlp** [soumyaxyz/abstractAnalysis#1]
Due to updates of Python versions and dependency libs, the code need an update too.
It's a very good project!

**Comment by soumyaxyz** [comment]
Hi slxienlp,

Thank you for your feedback and for taking an interest in improving this project!

I appreciate your suggestion to add more annotations and improve the requirements file. Since this project was originally coded in 2019, there might be several areas that could benefit from updates and enhancements.

While I'm not actively maintaining this project, I'm open to contributions. If you're interested, please feel free to fork the repository and submit pull requests with your suggested improvements. I'll review them and merge any changes that align with the project's goals.

Thank you again for your input and willingness to help improve the project!
